[package]
name = "api-client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shopkeep_core = { path = "../../core" }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
